//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLcafe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ban
    {
        public Ban()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public string MaBan { get; set; }
        public string TenBan { get; set; }
        public string MaPhucVu { get; set; }
        public int SucChua { get; set; }
    
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
