//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLcafe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSDatHang
    {
        public System.DateTime NgayDat { get; set; }
        public int SoLuong { get; set; }
        public string MaNguyenLieu { get; set; }
    
        public virtual NguyenLieu NguyenLieu { get; set; }
    }
}
