//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLcafe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public HoaDon()
        {
            this.CTHDs = new HashSet<CTHD>();
        }
    
        public string MaHoaDon { get; set; }
        public bool TrangThai { get; set; }
        public string MaBan { get; set; }
        public int TongTien { get; set; }
        public System.DateTime Ngay { get; set; }
        public string MaThuNgan { get; set; }
    
        public virtual Ban Ban { get; set; }
        public virtual ICollection<CTHD> CTHDs { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
