//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLcafe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public NguoiDung()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.Bans = new HashSet<Ban>();
        }
    
        public string MaNguoiDung { get; set; }
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public int QuyenHan { get; set; }
        public string TenNguoiDung { get; set; }
    
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual ICollection<Ban> Bans { get; set; }
    }
}
