//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLcafe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguyenLieu
    {
        public NguyenLieu()
        {
            this.DSDatHangs = new HashSet<DSDatHang>();
            this.PhieuNhaps = new HashSet<PhieuNhap>();
        }
    
        public string MaNguyenLieu { get; set; }
        public string TenNguyenLieu { get; set; }
        public int DonGiaNhap { get; set; }
        public string NhaCungCap { get; set; }
        public string DonVi { get; set; }
        public int SLConThieu { get; set; }
        public int TienConNo { get; set; }
    
        public virtual ICollection<DSDatHang> DSDatHangs { get; set; }
        public virtual ICollection<PhieuNhap> PhieuNhaps { get; set; }
    }
}
